name: 'CI'

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  MI_USER: ${{ secrets.MI_USER }}
  MI_PASS: ${{ secrets.MI_PASS }}
  MI_DID: ${{secrets.MI_DID}}
  OUT_HOME: false
  MI_API_PROXY: true
  MI_API_PROXY_URL: ${{ secrets.MI_API_PROXY_URL }}

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: zsj439453290/gitlab-ci-nodejs:linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          # 在这里添加构建和测试你的应用的命令
          yarn
          npm run build
      - name: Cov Test
        run: |
          # 在这里添加构建和测试你的应用的命令
          echo "secrets: ${{ toJson(secrets) }}"
          npm run test:cov
